version: '2'
services:
    cafvalidity_v2-app:
        image: cafvalidity_v2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cafvalidity_v2-mysql:3306/cafvalidity_v2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=cafvalidity_v2-elasticsearch:9300
        ports:
            - 8080:8080
    cafvalidity_v2-mysql:
        extends:
            file: mysql.yml
            service: cafvalidity_v2-mysql
    cafvalidity_v2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cafvalidity_v2-elasticsearch
